{
 "title": "Yacht tracker monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flink events in",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{task_name=\"Source:_raw_data_source____PROCESS______stream_key_by_map_operator__Map___stream_key_by_map_operator_\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink events out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=\"FlatMap_____PROCESS__Sink:_Writer____Sink:_Committer_\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network usage (received)",
   "type": "stat",
   "description": "IEC unit.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network usage (transmitted)",
   "type": "stat",
   "description": "IEC unit.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap memory in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pages/s" } },
   "targets": [
    { "expr": "rate(node_vmstat_pswpin[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Swap memory out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pages/s" } },
   "targets": [
    { "expr": "rate(node_vmstat_pswpout[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Late to on-time events ratio",
   "type": "timeseries",
   "description": "Each point represents the average rate of late to on-time events from last minute.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_1[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_1[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_2[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_2[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_3[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_3[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_4[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_4[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_5[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_5[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(flink_taskmanager_job_task_operator_late_device_6[1m])))\n/\nsum((rate(flink_taskmanager_job_task_operator_on_time_device_6[1m]) + 0.0000001))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time backpressured",
   "type": "timeseries",
   "description": "Non 0 values mean Flink can't push records downstream.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "description": "Error logs from all microservices.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} | detected_level=\"error\""
    }
   ]
  },
  {
   "title": "Average processing time for an event",
   "type": "timeseries",
   "description": "Average processing time for an event in last 5 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_time_counter_ms[5m])\n/\non(job, operator)\n(rate(flink_taskmanager_job_task_operator_total_on_time_events[5m]) + 0.00001)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}