services:
  timescaledb:
    image: timescale/timescaledb:2.19.1-pg17
    container_name: tsdb-regaty
    environment:
      POSTGRES_USER: karol
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tsdb
    ports:
      - "5432:5432"
    restart: no
    volumes:
      - tsdb-regaty:/var/lib/postgresql/data
      - ./tsdb/db-setup.sql:/docker-entrypoint-initdb.d/init.sql

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka-regaty
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1 # understand what wach of those do
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka-data:/tmp/kraft-combined-logs

    
volumes:
  tsdb-regaty:
  kafka-regaty: # seems like kafka doesnt get its volume? check it

