services:

  timescaledb:
    image: timescale/timescaledb:2.19.1-pg17
    container_name: tsdb
    #healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U karol -d tsdb"]
      #interval: 5s
      #timeout: 5s
      #retries: 10
    environment:
      POSTGRES_USER: karol
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tsdb
    ports:
      - "5432:5432"
    restart: no
    volumes:
      - tsdb-regaty:/var/lib/postgresql/data
      - ./tsdb/db_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - regaty-network


  broker: # for production consider disabling automatic topic creation
    image: apache/kafka:4.0.0
    container_name: broker
    #healthcheck:
      #test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      #interval: 5s
      #timeout: 10s
      #retries: 5
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    volumes:
      - kafka-regaty:/tmp/broker-logs
    networks:
      - regaty-network
    
  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:9092
    depends_on:
      - broker
    networks:
      - regaty-network

  
volumes:
  tsdb-regaty:
  kafka-regaty:

networks:
  regaty-network:
    name: regaty-network
    driver: bridge
    external: true
  default:
    external: false
    name: none