services:

  prometheus:
    image: prom/prometheus:v3.5.0-rc.0
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=2d"
    networks:
      - regaty-network

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/grafana
    depends_on:
      - prometheus
    networks:
      - regaty-network

  mimir:
    image: grafana/mimir:2.15.3
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - "--config.file=/etc/mimir/mimir.yaml"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - regaty-network

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    command:
      - "--config.file=/etc/loki/loki.yaml"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - regaty-network

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - regaty-network

networks:
  regaty-network:
    external: true
    name: regaty-network