services:

  prometheus:
    image: prom/prometheus:v3.5.0-rc.0
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
      - "--web.enable-lifecycle"
    networks:
      - regaty-network

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/grafana
    depends_on:
      - prometheus
    networks:
      - regaty-network

  # mimir:
  #   image:

  # loki:
  #   image: grafana/loki:3.5.1

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.52.0

networks:
  regaty-network:
    external: true
    name: regaty-network