services:

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards/json:/etc/grafana/provisioning/dashboards/json
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
    # environment settings added for the ease of use, not recommaneded in the production setting
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - regaty-network

  alloy:
    image: grafana/alloy:v1.10.0
    container_name: alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - ../logs:/logs
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    privileged: true
    networks:
      - regaty-network

  mimir:
    image: grafana/mimir:2.15.3
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - "--config.file=/etc/mimir/mimir.yaml"
    restart: unless-stopped
    networks:
      - regaty-network

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    command:
      - "--config.file=/etc/loki/loki.yaml"
    restart: unless-stopped
    depends_on:
      - mimir
    networks:
      - regaty-network

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    restart: unless-stopped
    networks:
      - regaty-network

networks:
  regaty-network:
    external: true
    name: regaty-network