services:

  jobmanager:
    build:
      context: ./flink_stream_processor/
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"
    command: jobmanager
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    networks:
      - regaty-network

  taskmanager:
    build:
      context: ./flink_stream_processor/
    container_name: taskmanager
    ports:
      - "9250:9249"
    command: taskmanager
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    networks:
      - regaty-network

networks:
  regaty-network:
    external: true
    name: regaty-network