services:

  jobmanager:
    build:
      context: ./flink_stream_processor/
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249

  taskmanager:
    build:
      context: ./flink_stream_processor/
    container_name: taskmanager
    command: taskmanager
    # see if you can just - them w/o flink_props=
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249

networks:
  regaty-network:
    external: true
    name: regaty-network