global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [prometheus:9090]

  - job_name: "flink"
    static_configs:
      - targets: ['jobmanager:9249', 'taskmanager:9249']