datasources:
  - name: loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    editable: false

  - name: mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    editable: false