services:

  flask:
    build:
      context: .
    container_name: flask
    volumes:
      - ./webapp:/opt/flask
    ports:
      - 5001:5000
    networks:
      - regaty-network

networks:
  regaty-network:
    external: true
    name: regaty-network