name: build & push data generator image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image'
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./data_generator/
          push: true
          tags: ghcr.io/${{ github.repository }}/data_generator:${{ github.event.inputs.tag || 'latest' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/data-generator:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/data-generator:cache,mode=max
