name: ci-data-generator

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/karol-ostrowski/yacht-tracker/data-generator:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: download pytest
        run: pip install pytest==8.4.1

      - name: run tests
        run: pytest tests/unit/data_generator