name: tests

on:
  push:
    branches:
      - "**"

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.4.1
          pip install pytest-mock==3.14.1
      - name: Test with pytest
        run: pytest